POST http://localhost:5500/api/item
Content-Type: application/json

{
    "item": "My second todo item"
}

###

GET http://localhost:5500/api/items
Content-Type: application/json

###

PUT http://localhost:5500/api/item/6314e918958795d3f4867e60
Content-Type: application/json

{
    "item": "My second updated todo item"
}

###

DELETE http://localhost:5500/api/item/6314e918958795d3f4867e60
Content-Type: application/json